CREATE TABLE MEMBER_TABLE (
      MEMBER_ID              NUMBER(11) CONSTRAINT PK_MEMBER_ID PRIMARY KEY,
      MEMBER_PASSWORD        VARCHAR2(16) ,
      MEMBER_MAIL            VARCHAR2(30),
      MEMBER_PHONE_NUMBER    NUMBER(11)
);

CREATE TABLE LOGIN_LOG (
      MEMBER_ID           NUMBER(11),
      LOGIN_DATE          DATE,  
      CONSTRAINT FK_lOGIN_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER_TABLE(MEMBER_ID)
);
      
CREATE TABLE HOTEL_ADMIN (
      TAX_NUMBER        NUMBER(10) CONSTRAINT PK_TAX_NUMBER PRIMARY KEY,
      HOTEL_NAME        VARCHAR2(20),
      TAX_ADMINSTRATION VARCHAR2(30),
      MEMBER_ID         NUMBER(11),
      CONSTRAINT FK_HOTAL_ADMIN_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER_TABLE(MEMBER_ID)
);

CREATE TABLE CUSTOMER (
      TC                NUMBER(11) CONSTRAINT PK_CUSTOMER_TC PRIMARY KEY,
      CUSTOMER_NAME     VARCHAR2(20),
      CUSTOMER_SURNAME  VARCHAR2(20),
      CUSTOMER_AGE      NUMBER(3),
      MEMBER_ID         NUMBER(11),
      CONSTRAINT FK_CUSTOMER_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER_TABLE(MEMBER_ID)
);

CREATE TABLE CUSTOMER_CARD (
      CUSTOMER_CARD_ID  NUMBER(11) CONSTRAINT PK_CUSTOMER_CARD_ID PRIMARY KEY,
      CARD_POINT        NUMBER(10,2),
      CUSTOMER_TC       NUMBER(11),
      CONSTRAINT FK_CARD_CUSTOMER_TC FOREIGN KEY (CUSTOMER_TC) REFERENCES CUSTOMER(TC)
);

CREATE TABLE GUEST (
      PHONE_NUMBER      NUMBER(11) CONSTRAINT PK_PHONE_NUMBER PRIMARY KEY,
      GUEST_NAME        VARCHAR2(20),
      GUEST_SURNAME     VARCHAR2(20),
      GUEST_MAIL        VARCHAR2(30),
      CUSTOMER_TC       NUMBER(11),
      CONSTRAINT FK_GUEST_CUSTOMER_TC FOREIGN KEY (CUSTOMER_TC) REFERENCES CUSTOMER(TC)
);

CREATE TABLE PAYMENT_TYPE (
      PAYMENT_TYPE_ID             NUMBER(11) CONSTRAINT PK_PAYMENT_TYPE_ID PRIMARY KEY,
      PAYMENT_TYPE_DEFINATION    VARCHAR2(30)   
);

CREATE TABLE PAYMENT (
      PAYMENT_ID          NUMBER(11) CONSTRAINT PK_PAYMENT_ID PRIMARY KEY,
      AMOUNT              NUMBER(20,2),
      PAYMENT_TYPE_ID      NUMBER(8),
      CONSTRAINT FK_PAYMENT_TYPE_ID  FOREIGN KEY (PAYMENT_TYPE_ID ) REFERENCES PAYMENT_TYPE(PAYMENT_TYPE_ID)
);

CREATE TABLE BOOKING (
      BOOKING_ID        NUMBER(11) CONSTRAINT PK_BOOKING_ID PRIMARY KEY,
      BOOKING_DATE      DATE,
      CUSTOMER_TC       NUMBER(11),
      PAYMENT_ID        NUMBER(8),
      CONSTRAINT FK_BOOKING_CUSTOMER_TC FOREIGN KEY (CUSTOMER_TC) REFERENCES CUSTOMER(TC),
      CONSTRAINT FK_BOOKING_PAYMENT_ID FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);

CREATE TABLE SEARCH_LOG (
      LOG_ID            NUMBER(11),
      ROOM_TYPE         NUMBER(11),
      ROOM_PRICE        NUMBER(20,2),
      HOTEL_TYPE        NUMBER(11),
      HOTEL_SERVICE     NUMBER(8),
      CUSTOMER_TC       NUMBER(11),
      CONSTRAINT FK_SEARCH_CUSTOMER_TC FOREIGN KEY (CUSTOMER_TC) REFERENCES CUSTOMER(TC)
);

CREATE TABLE HOTEL_TYPE (
      HOTEL_TYPE_ID     NUMBER(11) CONSTRAINT PK_HOTEL_TYPE_ID PRIMARY KEY,
      HOTEL_TYPE_DEFINATION      VARCHAR2(30)
);

CREATE TABLE HOTEL (
      HOTEL_ID         NUMBER(11) CONSTRAINT PK_HOTEL_ID PRIMARY KEY,
      HOTEL_DESTIRIPCION         VARCHAR2(45),
      HOTEL_NAME        VARCHAR2(45),
      ADMIN_TAX_NUMBER     NUMBER(10),
      HOTEL_TYPE_ID       NUMBER(11),
      CONSTRAINT FK_HOTEL_ADMIN_TAX_NUMBER FOREIGN KEY (ADMIN_TAX_NUMBER) REFERENCES HOTEL_ADMIN(TAX_NUMBER),
      CONSTRAINT FK_HOTEL_HOTEL_TYPE_ID FOREIGN KEY (HOTEL_TYPE_ID) REFERENCES HOTEL_TYPE(HOTEL_TYPE_ID)
);

CREATE TABLE HOTEL_SERVICE (
      HOTEL_SERVICE_ID         NUMBER(11) CONSTRAINT PK_SERVICE_ID PRIMARY KEY,
      SERVICE_PRICE         NUMBER(20,2),
      SERVICE_NAME        VARCHAR2(60),
      HOTEL_ID       NUMBER(11),
      CONSTRAINT FK_SERVICE_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);

CREATE TABLE HOTEL_HAS_SEARCH_LOG (
      HOTEL_ID         NUMBER(11),
      CUSTOMER_TC     NUMBER(11),
      CONSTRAINT FK_HOTEL_SEARCH_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID),
      CONSTRAINT FK_HOTEL_SEARCH_CUSTOMER_TC FOREIGN KEY (CUSTOMER_TC) REFERENCES CUSTOMER(TC)
);

CREATE TABLE COUNTRY (
      COUNTRY_ID     NUMBER(11) CONSTRAINT PK_COUNTRY_ID PRIMARY KEY,
      COUNTRY_NAME      VARCHAR2(30)
);

CREATE TABLE CITY (
      CITY_ID     NUMBER(11) CONSTRAINT PK_CITY_ID PRIMARY KEY,
      CITY_NAME      VARCHAR2(30),
      COUNTRY_ID     NUMBER(11),
      CONSTRAINT FK_CITY_COUNTRY_ID FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID)
);

CREATE TABLE ADDRESS (
      ADDRESS_DETAIL     VARCHAR2(60),
      CITY_ID     NUMBER(11),
      HOTEL_ID     NUMBER(11),
      CONSTRAINT FK_ADDRESS_CITY_ID FOREIGN KEY (CITY_ID) REFERENCES CITY(CITY_ID),
      CONSTRAINT FK_ADDRESS_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);

CREATE TABLE ROOM_TYPE (
      ROOM_TYPE_ID     NUMBER(11) CONSTRAINT PK_ROOM_TYPE_ID PRIMARY KEY,
      DESCRIPTION      VARCHAR2(45),
      BEDS_COUNT       NUMBER(11),
      PRICE            NUMBER(20,2)
);

CREATE TABLE ROOM_STATE (
      ROOM_STATE_DATE     NUMBER(11) CONSTRAINT PK_ROOM_STATE_DATE PRIMARY KEY,
      ROOM_STATE           NUMBER(1),
      PRICE            NUMBER(20,2)
);

CREATE TABLE ROOM_PRICE (
      ROOM_PRICE_DATE     NUMBER(11) CONSTRAINT PK_ROOM_PRICE_DATE PRIMARY KEY,
      PRICE_KDV          NUMBER(10,2),
      PRICE            NUMBER(20,2)
);

CREATE TABLE ROOM (
      ROOM_ID     NUMBER(11) CONSTRAINT PK_ROOM_ID PRIMARY KEY,
      ROOM_FLOOR        NUMBER(3),
      HOTEL_ID           NUMBER(11),
      ROOM_TYPE_ID      NUMBER(11),
      CONSTRAINT FK_ROOM_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID),
      CONSTRAINT FK_ROOM_TYPE_ID  FOREIGN KEY (ROOM_TYPE_ID ) REFERENCES ROOM_TYPE(ROOM_TYPE_ID)
);

CREATE TABLE ROOM_HAS_ROOM_STATE (
      ROOM_ID           NUMBER(11),
      HOTEL_ID          NUMBER(11),
      ROOM_TYPE_ID      NUMBER(11),
      ROOM_STATE_DATE      NUMBER(11),
      CONSTRAINT FK_ROOM_HASS_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
      CONSTRAINT FK_ROOM_HASS_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID),
      CONSTRAINT FK_ROOM_HASS_TYPE_ID  FOREIGN KEY (ROOM_TYPE_ID ) REFERENCES ROOM_TYPE(ROOM_TYPE_ID),
      CONSTRAINT FK_ROOM_HAS_STATE_DATE FOREIGN KEY (ROOM_STATE_DATE ) REFERENCES ROOM_STATE(ROOM_STATE_DATE)
);

CREATE TABLE ROOM_HAS_ROOM_PRICE (
      ROOM_ID           NUMBER(11),
      HOTEL_ID          NUMBER(11),
      ROOM_TYPE_ID      NUMBER(11),
      ROOM_PRICE_DATE      NUMBER(11),
      CONSTRAINT FK_ROOM_HASP_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
      CONSTRAINT FK_ROOM_HASP_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID),
      CONSTRAINT FK_ROOM_HASP_TYPE_ID  FOREIGN KEY (ROOM_TYPE_ID ) REFERENCES ROOM_TYPE(ROOM_TYPE_ID),
      CONSTRAINT FK_ROOM_HAS_PRICE_DATE FOREIGN KEY (ROOM_PRICE_DATE) REFERENCES ROOM_PRICE(ROOM_PRICE_DATE)
);

CREATE TABLE FEEDBACK (
      FEEDBACK_ID       NUMBER(11) CONSTRAINT PK_FEEDBACK_ID PRIMARY KEY,
      FEEDBACK_DETAIL   VARCHAR2(45),
      FEEDBACK_SCORE    NUMBER(2),
      CUSTOMER_TC      NUMBER(11),
      HOTEL_ID         NUMBER(11),
      CONSTRAINT FK_FEEDBACK_CUSTOMER_TC FOREIGN KEY (CUSTOMER_TC) REFERENCES CUSTOMER(TC),
      CONSTRAINT FK_FEEDBACK_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);

CREATE OR REPLACE PROCEDURE INSERT_MEMBER_TABLE(
	   MEMBER_PASSWORD IN MEMBER_TABLE.MEMBER_PASSWORD%TYPE,
     MEMBER_MAIL IN MEMBER_TABLE.MEMBER_MAIL%TYPE,
     MEMBER_PHONE_NUMBER IN MEMBER_TABLE.MEMBER_PHONE_NUMBER%TYPE)
IS
BEGIN
  INSERT INTO MEMBER_TABLE ("MEMBER_PASSWORD","MEMBER_MAIL","MEMBER_PHONE_NUMBER")
  VALUES (MEMBER_PASSWORD,MEMBER_MAIL,MEMBER_PHONE_NUMBER);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_LOGIN_LOG(
	   MEMBER_ID IN LOGIN_LOG.MEMBER_ID%TYPE)
IS
BEGIN
  INSERT INTO LOGIN_LOG ("MEMBER_ID")
  VALUES (MEMBER_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_HOTEL_ADMIN(
     HOTEL_NAME  IN HOTEL_ADMIN.HOTEL_NAME%TYPE,
     TAX_ADMINSTRATION  IN HOTEL_ADMIN.TAX_ADMINSTRATION%TYPE,
     MEMBER_ID  IN HOTEL_ADMIN.MEMBER_ID%TYPE)
IS
BEGIN
  INSERT INTO HOTEL_ADMIN ( "HOTEL_NAME","TAX_ADMINSTRATION","MEMBER_ID")
  VALUES (HOTEL_NAME,TAX_ADMINSTRATION,MEMBER_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_CUSTOMER(
     CUSTOMER_NAME  IN CUSTOMER.CUSTOMER_NAME%TYPE,
     CUSTOMER_SURNAME  IN CUSTOMER.CUSTOMER_SURNAME%TYPE,
     CUSTOMER_AGE  IN CUSTOMER.CUSTOMER_AGE%TYPE,
     MEMBER_ID   IN CUSTOMER.MEMBER_ID%TYPE)
IS
BEGIN
  INSERT INTO CUSTOMER ("CUSTOMER_NAME","CUSTOMER_SURNAME","CUSTOMER_AGE","MEMBER_ID")
  VALUES (CUSTOMER_NAME,CUSTOMER_SURNAME,CUSTOMER_AGE,MEMBER_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_CUSTOMER_CARD(
     CARD_POINT IN CUSTOMER_CARD.CARD_POINT%TYPE,
     CUSTOMER_TC IN CUSTOMER_CARD.CUSTOMER_TC%TYPE)
IS
BEGIN
  INSERT INTO CUSTOMER_CARD ("CARD_POINT","CUSTOMER_TC")
  VALUES (CARD_POINT, CUSTOMER_TC);
  COMMIT;
END;
/


CREATE OR REPLACE PROCEDURE INSERT_GUEST(
     GUEST_NAME IN GUEST.GUEST_NAME%TYPE,
     GUEST_SURNAME IN GUEST.GUEST_SURNAME%TYPE,
     GUEST_MAIL IN GUEST.GUEST_MAIL%TYPE,
     CUSTOMER_TC IN GUEST.CUSTOMER_TC%TYPE)
IS
BEGIN
  INSERT INTO GUEST ("GUEST_NAME", "GUEST_SURNAME", "GUEST_MAIL", "CUSTOMER_TC")
  VALUES (GUEST_NAME, GUEST_SURNAME, GUEST_MAIL, CUSTOMER_TC);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_PAYMENT_TYPE(
     PAYMENT_TYPE_DEFINATION IN PAYMENT_TYPE.PAYMENT_TYPE_DEFINATION%TYPE)
IS
BEGIN
  INSERT INTO PAYMENT_TYPE ("PAYMENT_TYPE_DEFINATION")
  VALUES (PAYMENT_TYPE_DEFINATION);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_PAYMENT(
     PAYMENT_TYPE_ID IN PAYMENT.PAYMENT_TYPE_ID%TYPE,
     AMOUNT IN PAYMENT.AMOUNT%TYPE)
IS
BEGIN
  INSERT INTO PAYMENT ("PAYMENT_TYPE_ID", "AMOUNT")
  VALUES (PAYMENT_TYPE_ID, AMOUNT);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_BOOKING(
     BOOKING_DATE IN BOOKING.BOOKING_DATE%TYPE,
     CUSTOMER_TC IN BOOKING.CUSTOMER_TC%TYPE,
     PAYMENT_ID IN BOOKING.PAYMENT_ID%TYPE)
IS
BEGIN
  INSERT INTO BOOKING ("BOOKING_DATE", "CUSTOMER_TC", "PAYMENT_ID")
  VALUES (BOOKING_DATE, CUSTOMER_TC, PAYMENT_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_SEARCH_LOG(
     ROOM_TYPE IN SEARCH_LOG.ROOM_TYPE%TYPE,
     ROOM_PRICE IN SEARCH_LOG.ROOM_PRICE%TYPE,
     HOTEL_TYPE IN SEARCH_LOG.HOTEL_TYPE%TYPE,
     HOTEL_SERVICE IN SEARCH_LOG.HOTEL_SERVICE%TYPE,
     CUSTOMER_TC IN SEARCH_LOG.CUSTOMER_TC%TYPE)
IS
BEGIN
  INSERT INTO SEARCH_LOG ("ROOM_TYPE", "ROOM_PRICE", "HOTEL_TYPE", "HOTEL_SERVICE", "CUSTOMER_TC")
  VALUES (ROOM_TYPE, ROOM_PRICE, HOTEL_TYPE, HOTEL_SERVICE, CUSTOMER_TC);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_HOTEL_TYPE(
     HOTEL_TYPE_DEFINATION IN HOTEL_TYPE.HOTEL_TYPE_DEFINATION%TYPE)
IS
BEGIN
  INSERT INTO HOTEL_TYPE ("HOTEL_TYPE_DEFINATION")
  VALUES (HOTEL_TYPE_DEFINATION);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_HOTEL(
     HOTEL_DESTIRIPCION IN HOTEL.HOTEL_DESTIRIPCION%TYPE,
     HOTEL_NAME IN HOTEL.HOTEL_NAME%TYPE,
     ADMIN_TAX_NUMBER IN HOTEL.ADMIN_TAX_NUMBER%TYPE,
     HOTEL_TYPE_ID IN HOTEL.HOTEL_TYPE_ID%TYPE)
IS
BEGIN
  INSERT INTO HOTEL ("HOTEL_DESTIRIPCION", "HOTEL_NAME", "ADMIN_TAX_NUMBER", "HOTEL_TYPE_ID")
  VALUES (HOTEL_DESTIRIPCION, HOTEL_NAME, ADMIN_TAX_NUMBER, HOTEL_TYPE_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_HOTEL_SERVICE(
     SERVICE_PRICE IN HOTEL_SERVICE.SERVICE_PRICE%TYPE,
     SERVICE_NAME IN HOTEL_SERVICE.SERVICE_NAME%TYPE,
     HOTEL_ID IN HOTEL_SERVICE.HOTEL_ID%TYPE)
IS
BEGIN
  INSERT INTO HOTEL_SERVICE ("SERVICE_PRICE", "SERVICE_NAME", "HOTEL_ID")
  VALUES (SERVICE_PRICE, SERVICE_NAME, HOTEL_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_HOTEL_HAS_SEARCH_LOG(
     HOTEL_ID IN HOTEL_HAS_SEARCH_LOG.HOTEL_ID%TYPE,
     CUSTOMER_TC IN HOTEL_HAS_SEARCH_LOG.CUSTOMER_TC%TYPE)
IS
BEGIN
  INSERT INTO HOTEL_HAS_SEARCH_LOG ("HOTEL_ID", "CUSTOMER_TC")
  VALUES (HOTEL_ID, CUSTOMER_TC);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_COUNTRY(
	   COUNTRY_NAME IN COUNTRY.COUNTRY_NAME%TYPE)
IS
BEGIN
  INSERT INTO COUNTRY ("COUNTRY_NAME")
  VALUES (COUNTRY_NAME);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_CITY(
	   CITY_NAME IN CITY.CITY_NAME%TYPE,
	   COUNTRY_ID IN CITY.COUNTRY_ID%TYPE)
IS
BEGIN
  INSERT INTO CITY ("CITY_NAME", "COUNTRY_ID")
  VALUES (CITY_NAME, COUNTRY_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_ADDRESS(
     ADDRESS_DETAIL IN ADDRESS.ADDRESS_DETAIL%TYPE,
     CITY_ID IN ADDRESS.CITY_ID%TYPE,
     HOTEL_ID IN ADDRESS.HOTEL_ID%TYPE)
IS
BEGIN
  INSERT INTO ADDRESS ("ADDRESS_DETAIL", "CITY_ID", "HOTEL_ID")
  VALUES (ADDRESS_DETAIL, CITY_ID, HOTEL_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_ROOM_TYPE(
     DESCRIPTION IN ROOM_TYPE.DESCRIPTION%TYPE,
     BEDS_COUNT IN ROOM_TYPE.BEDS_COUNT%TYPE,
     PRICE IN ROOM_TYPE.PRICE%TYPE)
IS
BEGIN
  INSERT INTO ROOM_TYPE ("DESCRIPTION", "BEDS_COUNT", "PRÝCE")
  VALUES (DESCRIPTÝON, BEDS_COUNT, PRÝCE);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_ROOM_STATE(
     ROOM_STATE IN ROOM_STATE.ROOM_STATE%TYPE,
     PRICE IN ROOM_STATE.PRICE%TYPE)
IS
BEGIN
  INSERT INTO ROOM_STATE ("ROOM_STATE", "PRICE")
  VALUES (ROOM_STATE, PRICE);
  
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_ROOM_PRICE(
     PRICE_KDV IN ROOM_PRICE.PRICE_KDV%TYPE,
     PRICE IN ROOM_PRICE.PRICE%TYPE)
IS
BEGIN
  INSERT INTO ROOM_PRICE ("PRICE_KDV", "PRICE")
  VALUES (PRICE_KDV, PRICE);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_ROOM(
     ROOM_FLOOR IN ROOM.ROOM_FLOOR%TYPE,
     HOTEL_ID IN ROOM.HOTEL_ID%TYPE,
     ROOM_TYPE_ID IN ROOM.ROOM_TYPE_ID%TYPE)
IS
BEGIN
  INSERT INTO ROOM ("ROOM_FLOOR", "HOTEL_ID", "ROOM_TYPE_ID")
  VALUES (ROOM_FLOOR, HOTEL_ID, ROOM_TYPE_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_ROOM_HAS_ROOM_STATE(
     ROOM_ID IN ROOM_HAS_ROOM_STATE.ROOM_ID%TYPE,
     HOTEL_ID IN ROOM_HAS_ROOM_STATE.HOTEL_ID%TYPE,
     ROOM_TYPE_ID IN ROOM_HAS_ROOM_STATE.ROOM_TYPE_ID%TYPE,
     ROOM_STATE_DATE IN ROOM_HAS_ROOM_STATE.ROOM_STATE_DATE%TYPE)
IS
BEGIN
  INSERT INTO ROOM_HAS_ROOM_STATE ("ROOM_ID", "HOTEL_ID", "ROOM_TYPE_ID", "ROOM_STATE_DATE")
  VALUES (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, ROOM_STATE_DATE);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_ROOM_HAS_ROOM_PRICE(
     ROOM_ID IN ROOM_HAS_ROOM_PRICE.ROOM_ID%TYPE,
     HOTEL_ID IN ROOM_HAS_ROOM_PRICE.HOTEL_ID%TYPE,
     ROOM_TYPE_ID IN ROOM_HAS_ROOM_PRICE.ROOM_TYPE_ID%TYPE,
     ROOM_PRICE_DATE IN ROOM_HAS_ROOM_PRICE.ROOM_PRICE_DATE%TYPE)
IS
BEGIN
  INSERT INTO ROOM_HAS_ROOM_PRICE ("ROOM_ID", "HOTEL_ID", "ROOM_TYPE_ID", "ROOM_PRICE_DATE")
  VALUES (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, ROOM_PRICE_DATE);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_FEEDBACK(
     FEEDBACK_DETAIL IN FEEDBACK.FEEDBACK_DETAIL%TYPE,
     FEEDBACK_SCORE IN FEEDBACK.FEEDBACK_SCORE%TYPE,
     CUSTOMER_TC IN FEEDBACK.CUSTOMER_TC%TYPE,
     HOTEL_ID IN FEEDBACK.HOTEL_ID%TYPE)
IS
BEGIN
  INSERT INTO FEEDBACK ("FEEDBACK_DETAIL", "FEEDBACK_SCORE", "CUSTOMER_TC", "HOTEL_ID")
  VALUES (FEEDBACK_DETAIL, FEEDBACK_SCORE, CUSTOMER_TC, HOTEL_ID);
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_MEMBER_TABLE(
  DMEMBER_ID IN MEMBER_TABLE.MEMBER_ID%TYPE)
IS
BEGIN
  DELETE MEMBER_TABLE WHERE MEMBER_TABLE.MEMBER_ID = DMEMBER_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_LOGIN_LOG(
  DMEMBER_ID IN LOGIN_LOG.MEMBER_ID%TYPE)
IS
BEGIN
  DELETE LOGIN_LOG WHERE LOGIN_LOG.MEMBER_ID = DMEMBER_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_HOTEL_ADMIN(
  DTAX_NUMBER IN HOTEL_ADMIN.TAX_NUMBER%TYPE)
IS
BEGIN
  DELETE HOTEL_ADMIN WHERE HOTEL_ADMIN.TAX_NUMBER = DTAX_NUMBER;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_CUSTOMER(
  DTC IN CUSTOMER.TC%TYPE)
IS
BEGIN
  DELETE CUSTOMER WHERE CUSTOMER.TC = DTC;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_CUSTOMER_CARD(
  DCUSTOMER_CARD_ID IN CUSTOMER_CARD.CUSTOMER_CARD_ID%TYPE)
IS
BEGIN
  DELETE CUSTOMER_CARD WHERE CUSTOMER_CARD.CUSTOMER_CARD_ID = DCUSTOMER_CARD_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_GUEST(
  DPHONE_NUMBER IN GUEST.PHONE_NUMBER%TYPE)
IS
BEGIN
  DELETE GUEST WHERE GUEST.PHONE_NUMBER = DPHONE_NUMBER;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_PAYMENT_TYPE(
  DPAYMENT_TYPE_ID IN PAYMENT_TYPE.PAYMENT_TYPE_ID%TYPE)
IS
BEGIN
  DELETE PAYMENT_TYPE WHERE PAYMENT_TYPE.PAYMENT_TYPE_ID = DPAYMENT_TYPE_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_PAYMENT(
  DPAYMENT_ID IN PAYMENT.PAYMENT_ID%TYPE)
IS
BEGIN
  DELETE PAYMENT WHERE PAYMENT.PAYMENT_ID = DPAYMENT_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_BOOKING(
  DBOOKING_ID IN BOOKING.BOOKING_ID%TYPE)
IS
BEGIN
  DELETE BOOKING where BOOKING.BOOKING_ID  = DBOOKING_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_SEARCH_LOG(
  DLOG_ID IN SEARCH_LOG.LOG_ID%TYPE)
IS
BEGIN
  DELETE SEARCH_LOG WHERE SEARCH_LOG.LOG_ID  = DLOG_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_HOTEL_TYPE(
  DHOTEL_TYPE_ID IN HOTEL_TYPE.HOTEL_TYPE_ID%TYPE)
IS
BEGIN
  DELETE HOTEL_TYPE WHERE HOTEL_TYPE.HOTEL_TYPE_ID  = DHOTEL_TYPE_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_HOTEL(
  DHOTEL_ID IN HOTEL.HOTEL_ID%TYPE)
IS
BEGIN
  DELETE HOTEL WHERE HOTEL.HOTEL_ID  = DHOTEL_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_HOTEL_SERVICE(
  DHOTEL_SERVICE_ID IN HOTEL_SERVICE.HOTEL_SERVICE_ID%TYPE)
IS
BEGIN
  DELETE HOTEL_SERVICE WHERE HOTEL_SERVICE.HOTEL_SERVICE_ID  = DHOTEL_SERVICE_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_HOTEL_HAS_SEARCH_LOGE(
  DHOTEL_ID IN HOTEL_HAS_SEARCH_LOG.HOTEL_ID%TYPE)
IS
BEGIN
  DELETE HOTEL_HAS_SEARCH_LOG WHERE HOTEL_HAS_SEARCH_LOG.HOTEL_ID  = DHOTEL_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_COUNTRY(
  DCOUNTRY_ID IN COUNTRY.COUNTRY_ID%TYPE)
IS
BEGIN
  DELETE COUNTRY WHERE COUNTRY.COUNTRY_ID  = DCOUNTRY_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_CITY(
  DCITY_ID IN CITY.CITY_ID%TYPE)
IS
BEGIN
  DELETE CITY WHERE CITY.CITY_ID  = DCITY_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_ADDRESS(
  DADDRESS_DETAIL IN ADDRESS.ADDRESS_DETAIL%TYPE)
IS
BEGIN
  DELETE ADDRESS where ADDRESS.ADDRESS_DETAIL  = DADDRESS_DETAIL;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_ROOM_TYPE(
  DROOM_TYPE_ID IN ROOM_TYPE.ROOM_TYPE_ID%TYPE)
IS
BEGIN
  DELETE ROOM_TYPE where ROOM_TYPE.ROOM_TYPE_ID  = DROOM_TYPE_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_ROOM_STATE(
  DROOM_STATE_DATE IN ROOM_STATE.ROOM_STATE_DATE%TYPE)
IS
BEGIN
  DELETE ROOM_STATE where ROOM_STATE.ROOM_STATE_DATE  = DROOM_STATE_DATE;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_ROOM_PRICE(
  DROOM_PRICE_DATE IN ROOM_PRICE.ROOM_PRICE_DATE%TYPE)
IS
BEGIN
  DELETE ROOM_PRICE where ROOM_PRICE.ROOM_PRICE_DATE  = DROOM_PRICE_DATE;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_ROOM(
  DROOM_ID IN ROOM.ROOM_ID%TYPE)
IS
BEGIN
  DELETE ROOM where ROOM.ROOM_ID  = DROOM_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_ROOM_HAS_ROOM_STATE(
  DROOM_ID IN ROOM_HAS_ROOM_STATE.ROOM_ID%TYPE)
IS
BEGIN
  DELETE ROOM_HAS_ROOM_STATE where ROOM_HAS_ROOM_STATE.ROOM_ID  = DROOM_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_ROOM_HAS_ROOM_PRICE(
  DROOM_ID IN ROOM_HAS_ROOM_PRICE.ROOM_ID%TYPE)
IS
BEGIN
  DELETE ROOM_HAS_ROOM_PRICE where ROOM_HAS_ROOM_PRICE.ROOM_ID  = DROOM_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE DELETE_FEEDBACK(
  DFEEDBACK_ID IN FEEDBACK.FEEDBACK_ID%TYPE)
IS
BEGIN
  DELETE FEEDBACK where FEEDBACK.FEEDBACK_ID  = DFEEDBACK_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_MEMBER_TABLE(
	   UMEMBER_ID IN MEMBER_TABLE.MEMBER_ID%TYPE,
	   UMEMBER_PASSWORD IN MEMBER_TABLE.MEMBER_PASSWORD%TYPE,
     UMEMBER_MAIL IN MEMBER_TABLE.MEMBER_MAIL%TYPE,
     UMEMBER_PHONE_NUMBER IN MEMBER_TABLE.MEMBER_PHONE_NUMBER%TYPE
     )
IS
BEGIN
  UPDATE MEMBER_TABLE SET MEMBER_TABLE.MEMBER_PASSWORD = UMEMBER_PASSWORD,
                          MEMBER_TABLE.MEMBER_MAIL = UMEMBER_MAIL,
                          MEMBER_TABLE.MEMBER_PHONE_NUMBER = UMEMBER_PHONE_NUMBER
  WHERE MEMBER_TABLE.MEMBER_ID = UMEMBER_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_LOGIN_LOG(
	   UMEMBER_ID IN LOGIN_LOG.MEMBER_ID%TYPE,
	   ULOGIN_DATE IN LOGIN_LOG.LOGIN_DATE%TYPE
     )
IS
BEGIN
  UPDATE LOGIN_LOG SET LOGIN_LOG.MEMBER_ID = UMEMBER_ID
  WHERE LOGIN_LOG.LOGIN_DATE = ULOGIN_DATE;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_HOTEL_ADMIN(
	   UTAX_NUMBER IN HOTEL_ADMIN.TAX_NUMBER%TYPE,
	   UHOTEL_NAME IN HOTEL_ADMIN.HOTEL_NAME%TYPE,
     UTAX_ADMINSTRATION IN HOTEL_ADMIN.TAX_ADMINSTRATION%TYPE,
     UMEMBER_ID IN HOTEL_ADMIN.MEMBER_ID%TYPE
     )
IS
BEGIN
  UPDATE HOTEL_ADMIN SET HOTEL_ADMIN.HOTEL_NAME = UHOTEL_NAME,
                          HOTEL_ADMIN.TAX_ADMINSTRATION = UTAX_ADMINSTRATION,
                          HOTEL_ADMIN.MEMBER_ID = UMEMBER_ID
  WHERE HOTEL_ADMIN.TAX_NUMBER = UTAX_NUMBER;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_CUSTOMER(
	   UTC IN CUSTOMER.TC%TYPE,
	   UCUSTOMER_NAME IN CUSTOMER.CUSTOMER_NAME%TYPE,
     UCUSTOMER_SURNAME IN CUSTOMER.CUSTOMER_SURNAME%TYPE,
     UCUSTOMER_AGE IN CUSTOMER.CUSTOMER_AGE%TYPE,
     UMEMBER_ID IN CUSTOMER.MEMBER_ID%TYPE
     )
IS
BEGIN
  UPDATE CUSTOMER SET CUSTOMER.CUSTOMER_NAME = UCUSTOMER_NAME,
                      CUSTOMER.CUSTOMER_SURNAME = UCUSTOMER_SURNAME,
                      CUSTOMER.CUSTOMER_AGE = UCUSTOMER_AGE, 
                      CUSTOMER.MEMBER_ID = UMEMBER_ID
  WHERE CUSTOMER.TC = UTC;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_CUSTOMER_CARD(
	   UCUSTOMER_CARD_ID IN CUSTOMER_CARD.CUSTOMER_CARD_ID%TYPE,
	   UCARD_POINT IN CUSTOMER_CARD.CARD_POINT%TYPE,
     UCUSTOMER_TC IN CUSTOMER_CARD.CUSTOMER_TC%TYPE
     )
IS
BEGIN
  UPDATE CUSTOMER_CARD SET CUSTOMER_CARD.CARD_POINT = UCARD_POINT,
                        CUSTOMER_CARD.CUSTOMER_TC = UCUSTOMER_TC
  WHERE CUSTOMER_CARD.CUSTOMER_CARD_ID = UCUSTOMER_CARD_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_GUEST(
	   UPHONE_NUMBER IN GUEST.PHONE_NUMBER%TYPE,
	   UGUEST_NAME IN GUEST.GUEST_NAME%TYPE,
     UGUEST_SURNAME IN GUEST.GUEST_SURNAME%TYPE,
     UGUEST_MAIL IN GUEST.GUEST_MAIL%TYPE,
     UCUSTOMER_TC IN GUEST.CUSTOMER_TC%TYPE
     )
IS
BEGIN
  UPDATE GUEST SET GUEST.GUEST_NAME = UGUEST_NAME,
                    GUEST.GUEST_SURNAME = UGUEST_SURNAME,
                    GUEST.GUEST_MAIL = UGUEST_MAIL,
                    GUEST.CUSTOMER_TC = UCUSTOMER_TC
  WHERE GUEST.PHONE_NUMBER = UPHONE_NUMBER;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_PAYMENT_TYPE(
	   UPAYMENT_TYPE_ID IN PAYMENT_TYPE.PAYMENT_TYPE_ID%TYPE,
	   UPAYMENT_TYPE_DEFINATION IN PAYMENT_TYPE.PAYMENT_TYPE_DEFINATION%TYPE
     )
IS
BEGIN
  UPDATE PAYMENT_TYPE SET PAYMENT_TYPE.PAYMENT_TYPE_DEFINATION = UPAYMENT_TYPE_DEFINATION
  WHERE PAYMENT_TYPE.PAYMENT_TYPE_ID = UPAYMENT_TYPE_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_PAYMENT(
	   UPAYMENT_ID IN PAYMENT.PAYMENT_ID%TYPE,
	   UAMOUNT IN PAYMENT.AMOUNT%TYPE,
     UPAYMENT_TYPE_ID IN PAYMENT.PAYMENT_TYPE_ID%TYPE
     )
IS
BEGIN
  UPDATE PAYMENT SET PAYMENT.AMOUNT = UAMOUNT,
                      PAYMENT.PAYMENT_TYPE_ID = UPAYMENT_TYPE_ID
  WHERE PAYMENT.PAYMENT_ID = UPAYMENT_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_BOOKING(
	   UBOOKING_ID IN BOOKING.BOOKING_ID%TYPE,
	   UBOOKING_DATE IN BOOKING.BOOKING_DATE%TYPE,
     UCUSTOMER_TC IN BOOKING.CUSTOMER_TC%TYPE,
     UPAYMENT_ID IN BOOKING.PAYMENT_ID%TYPE
     )
IS
BEGIN
  UPDATE BOOKING SET BOOKING.BOOKING_DATE = UBOOKING_DATE,
                      BOOKING.CUSTOMER_TC = UCUSTOMER_TC,
                      BOOKING.PAYMENT_ID = UPAYMENT_ID
  WHERE BOOKING.BOOKING_ID = UBOOKING_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_SEARCH_LOG(
    ULOG_ID IN SEARCH_LOG.LOG_ID%TYPE,
	   UROOM_TYPE IN SEARCH_LOG.ROOM_TYPE%TYPE,
	   UROOM_PRICE IN SEARCH_LOG.ROOM_PRICE%TYPE,
     UHOTEL_TYPE IN SEARCH_LOG.HOTEL_TYPE%TYPE,
     UHOTEL_SERVICE IN SEARCH_LOG.HOTEL_SERVICE%TYPE,
     UCUSTOMER_TC IN SEARCH_LOG.CUSTOMER_TC%TYPE
     )
IS
BEGIN
  UPDATE SEARCH_LOG SET SEARCH_LOG.ROOM_TYPE = UROOM_TYPE,
                        SEARCH_LOG.ROOM_PRICE = UROOM_PRICE,
                        SEARCH_LOG.HOTEL_TYPE = UHOTEL_TYPE,
                        SEARCH_LOG.HOTEL_SERVICE = UHOTEL_SERVICE,
                        SEARCH_LOG.CUSTOMER_TC = UCUSTOMER_TC
  WHERE SEARCH_LOG.LOG_ID = ULOG_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_HOTEL_TYPE(
	   UHOTEL_TYPE_ID IN HOTEL_TYPE.HOTEL_TYPE_ID%TYPE,
	   UHOTEL_TYPE_DEFINATION IN HOTEL_TYPE.HOTEL_TYPE_DEFINATION%TYPE
     )
IS
BEGIN
  UPDATE HOTEL_TYPE SET HOTEL_TYPE.HOTEL_TYPE_DEFINATION = UHOTEL_TYPE_DEFINATION
  WHERE HOTEL_TYPE.HOTEL_TYPE_ID = UHOTEL_TYPE_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_HOTEL(
	   UHOTEL_ID IN HOTEL.HOTEL_ID%TYPE,
	   UHOTEL_DESTIRIPCION IN HOTEL.HOTEL_DESTIRIPCION%TYPE,
     UHOTEL_NAME IN HOTEL.HOTEL_NAME%TYPE,
     UADMIN_TAX_NUMBER IN HOTEL.ADMIN_TAX_NUMBER%TYPE,
     UHOTEL_TYPE_ID IN HOTEL.HOTEL_TYPE_ID%TYPE
     )
IS
BEGIN
  UPDATE HOTEL SET HOTEL.HOTEL_DESTIRIPCION = UHOTEL_DESTIRIPCION,
                        HOTEL.HOTEL_NAME = UHOTEL_NAME,
                        HOTEL.ADMIN_TAX_NUMBER = UADMIN_TAX_NUMBER,
                        HOTEL.HOTEL_TYPE_ID = UHOTEL_TYPE_ID
  WHERE HOTEL.HOTEL_ID = UHOTEL_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_HOTEL_SERVICE(
	   UHOTEL_SERVICE_ID IN HOTEL_SERVICE.HOTEL_SERVICE_ID%TYPE,
	   USERVICE_PRICE IN HOTEL_SERVICE.SERVICE_PRICE%TYPE,
     USERVICE_NAME IN HOTEL_SERVICE.SERVICE_NAME%TYPE,
     UHOTEL_ID IN HOTEL_SERVICE.HOTEL_ID%TYPE
     )
IS
BEGIN
  UPDATE HOTEL_SERVICE SET HOTEL_SERVICE.SERVICE_PRICE = USERVICE_PRICE,
                          HOTEL_SERVICE.SERVICE_NAME = USERVICE_NAME,
                          HOTEL_SERVICE.HOTEL_ID = UHOTEL_ID
  WHERE HOTEL_SERVICE.HOTEL_SERVICE_ID = UHOTEL_SERVICE_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_COUNTRY(
	   UCOUNTRY_ID IN COUNTRY.COUNTRY_ID%TYPE,
	   UCOUNTRY_NAME IN COUNTRY.COUNTRY_NAME%TYPE
     )
IS
BEGIN
  UPDATE COUNTRY SET COUNTRY.COUNTRY_NAME = UCOUNTRY_NAME
  WHERE COUNTRY.COUNTRY_ID = UCOUNTRY_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_CITY(
	   UCITY_ID IN CITY.CITY_ID%TYPE,
	   UCITY_NAME IN CITY.CITY_NAME%TYPE,
     UCOUNTRY_ID IN CITY.COUNTRY_ID%TYPE
     )
IS
BEGIN
  UPDATE CITY SET CITY.CITY_NAME = UCITY_NAME,
                  CITY.COUNTRY_ID = UCOUNTRY_ID
  WHERE CITY.CITY_ID = UCITY_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_ADDRESS(
	   UPDATE_ADDRESS_DETAIL IN ADDRESS.ADDRESS_DETAIL%TYPE,
	   UCITY_ID IN ADDRESS.CITY_ID%TYPE,
	   UHOTEL_ID IN ADDRESS.HOTEL_ID%TYPE
     )
IS
BEGIN
  UPDATE ADDRESS SET ADDRESS.ADDRESS_DETAIL = UPDATE_ADDRESS_DETAIL,
                      ADDRESS.CITY_ID = UCITY_ID,
                      ADDRESS.HOTEL_ID =UHOTEL_ID
  WHERE ADDRESS.ADDRESS_DETAIL = UPDATE_ADDRESS_DETAIL;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_ROOM_TYPE(
	   UROOM_TYPE_ID IN ROOM_TYPE.ROOM_TYPE_ID%TYPE,
	   UDESCRIPTION IN ROOM_TYPE.DESCRIPTION%TYPE,
     UBEDS_COUNT IN ROOM_TYPE.BEDS_COUNT%TYPE,
     UPRICE IN ROOM_TYPE.PRICE%TYPE
     )
IS
BEGIN
  UPDATE ROOM_TYPE SET ROOM_TYPE.DESCRIPTION = UDESCRIPTION,
                        ROOM_TYPE.BEDS_COUNT = UBEDS_COUNT,
                        ROOM_TYPE.PRICE = PRICE
  WHERE ROOM_TYPE.ROOM_TYPE_ID = UROOM_TYPE_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_ROOM_STATE(
	   UROOM_STATE_DATE IN ROOM_STATE.ROOM_STATE_DATE%TYPE,
	   UROOM_STATE IN ROOM_STATE.ROOM_STATE%TYPE,
     UPRICE IN ROOM_STATE.PRICE%TYPE
     )
IS
BEGIN
  UPDATE ROOM_STATE SET ROOM_STATE.ROOM_STATE = UROOM_STATE,
                        ROOM_STATE.PRICE = UPRICE
  WHERE ROOM_STATE.ROOM_STATE_DATE = UROOM_STATE_DATE;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_ROOM_PRICE(
	   UROOM_PRICE_DATE IN ROOM_PRICE.ROOM_PRICE_DATE%TYPE,
	   UPRICE_KDV IN ROOM_PRICE.PRICE_KDV%TYPE,
     UPRICE IN ROOM_PRICE.PRICE%TYPE
     )
IS
BEGIN
  UPDATE ROOM_PRICE SET ROOM_PRICE.PRICE_KDV = UPRICE_KDV,
                        ROOM_PRICE.PRICE = UPRICE
  WHERE ROOM_PRICE.ROOM_PRICE_DATE = UROOM_PRICE_DATE;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_ROOM(
	   UROOM_ID IN ROOM.ROOM_ID%TYPE,
	   UROOM_FLOOR IN ROOM.ROOM_FLOOR%TYPE,
	   UHOTEL_ID IN ROOM.HOTEL_ID%TYPE,
	   UROOM_TYPE_ID IN ROOM.ROOM_TYPE_ID%TYPE
     )
IS
BEGIN
  UPDATE ROOM SET ROOM.ROOM_FLOOR = UROOM_FLOOR,
                  ROOM.HOTEL_ID = UHOTEL_ID,
                  ROOM.ROOM_TYPE_ID = UROOM_TYPE_ID
  WHERE ROOM.ROOM_ID = UROOM_ID;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE UPDATE_FEEDBACK(
	   UFEEDBACK_ID IN FEEDBACK.FEEDBACK_ID%TYPE,
	   UFEEDBACK_DETAIL IN FEEDBACK.FEEDBACK_DETAIL%TYPE,
     UFEEDBACK_SCORE IN FEEDBACK.FEEDBACK_SCORE%TYPE,
     UCUSTOMER_TC IN FEEDBACK.CUSTOMER_TC%TYPE,
     UHOTEL_ID IN FEEDBACK.HOTEL_ID%TYPE
     )
IS
BEGIN
  UPDATE FEEDBACK SET FEEDBACK.FEEDBACK_DETAIL = UFEEDBACK_DETAIL,
                        FEEDBACK.FEEDBACK_SCORE = UFEEDBACK_SCORE,
                        FEEDBACK.CUSTOMER_TC = UCUSTOMER_TC,
                        FEEDBACK.HOTEL_ID = UHOTEL_ID
  WHERE FEEDBACK.FEEDBACK_ID = UFEEDBACK_ID;
  COMMIT;
END;
/

create sequence squ_member_table
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_member_table
	before
	insert on member_table
	for each row
begin
	if :NEW.member_ýd is null then
    select squ_member_table.nextval into :new.member_ýd from dual;
  end if;
end trg_member_table;
/

create sequence squ_hotel_admin
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_hotel_admin
	before
	insert on hotel_admin
	for each row
begin
	if :new.tax_number is null then
    select squ_hotel_admin.nextval into :new.tax_number from dual;
  end if;
end trg_hotel_admin;
/

create sequence squ_customer
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_customer
	before
	insert on customer
	for each row
begin
	if :new.tc is null then
    select squ_customer.nextval into :new.tc from dual;
  end if;
end trg_customer;
/

create sequence squ_customer_card
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_customer_card
	before
	insert on customer_card
	for each row
begin
	if :new.customer_card_id is null then
    select squ_customer_card.nextval into :new.customer_card_id from dual;
  end if;
end trg_customer_card;
/

create sequence squ_guest
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_guest
	before
	insert on guest
	for each row
begin
	if :new.phone_number is null then
    select squ_guest.nextval into :new.phone_number from dual;
  end if;
end trg_guest;
/

create sequence squ_payment_type
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_payment_type
	before
	insert on payment_type
	for each row
begin
	if :new.payment_type_id is null then
    select squ_payment_type.nextval into :new.payment_type_id from dual;
  end if;
end trg_payment_type;
/

create sequence squ_payment
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_payment
	before
	insert on payment
	for each row
begin
	if :new.payment_id is null then
    select squ_payment.nextval into :new.payment_id from dual;
  end if;
end trg_payment;
/

create sequence squ_booking
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_booking
	before
	insert on booking
	for each row
begin
	if :new.booking_id is null then
    select squ_booking.nextval into :new.booking_id from dual;
  end if;
end trg_booking;
/

create sequence squ_search_log
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_search_log
	before
	insert on search_log
	for each row
begin
	if :new.log_ýd is null then
    select squ_search_log.nextval into :new.log_ýd from dual;
  end if;
end trg_search_log;
/

create sequence squ_hotel_type
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_hotel_type
	before
	insert on hotel_type
	for each row
begin
	if :new.hotel_type_id is null then
    select squ_hotel_type.nextval into :new.hotel_type_id from dual;
  end if;
end trg_hotel_type;
/

create sequence squ_hotel
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_hotel
	before
	insert on hotel
	for each row
begin
	if :new.hotel_id is null then
    select squ_hotel.nextval into :new.hotel_id from dual;
  end if;
end trg_hotel;
/

create sequence squ_hotel_service
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_hotel_service
	before
	insert on hotel_service
	for each row
begin
	if :new.hotel_service_id is null then
    select squ_hotel_service.nextval into :new.hotel_service_id from dual;
  end if;
end trg_hotel;
/
create sequence squ_country
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_country
	before
	insert on country
	for each row
begin
	if :new.country_id is null then
    select squ_country.nextval into :new.country_id from dual;
  end if;
end trg_country;
/

create sequence squ_city
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_city
	before
	insert on city
	for each row
begin
	if :new.city_id is null then
    select squ_city.nextval into :new.city_id from dual;
  end if;
end trg_city;
/

create sequence squ_room_type
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_room_type
	before
	insert on room_type
	for each row
begin
	if :new.room_type_id is null then
    select squ_room_type.nextval into :new.room_type_id from dual;
  end if;
end trg_room_type;
/

create sequence squ_room_state
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_room_state
	before
	insert on room_state
	for each row
begin
	if :new.room_state_date is null then
    select squ_room_state.nextval into :new.room_state_date from dual;
  end if;
end trg_room_state;
/

create sequence squ_room_price
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_room_price
	before
	insert on room_price
	for each row
begin
	if :new.room_price_date is null then
    select squ_room_price.nextval into :new.room_price_date from dual;
  end if;
end trg_room_price;
/

create sequence squ_room
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_room
	before
	insert on room
	for each row
begin
	if :new.room_id is null then
    select squ_room.nextval into :new.room_id from dual;
  end if;
end trg_room;
/

create sequence squ_feedback
minvalue 0
maxvalue 999999999
start with 1
increment by 1
nocache;
/
create or replace trigger trg_feedback
	before
	insert on feedback
	for each row
begin
	if :new.feedback_id is null then
    select squ_feedback.nextval into :new.feedback_id from dual;
  end if;
end trg_feedback;
/


create or replace trigger trg_login_log
	before
	insert on login_log
	for each row
begin
	if :new.login_date is null then
    select CURRENT_TIMESTAMP into :new.login_date from dual;
  end if;
end trg_login_log;
/