CREATE or REPLACE VIEW VIEW_HOTEL_SEARCH AS
SELECT HOTEL.HOTEL_NAME, HOTEL.HOTEL_DESTIRIPCION, AVG(FEEDBACK.FEEDBACK_SCORE) AS AVG_SCORE
  FROM HOTEL
  lEFT JOIN FEEDBACK
  ON HOTEL.HOTEL_ID = FEEDBACK.HOTEL_ID
  GROUP BY HOTEL.HOTEL_NAME,HOTEL.HOTEL_DESTIRIPCION;
  
CREATE or REPLACE VIEW VÝEW_PAYMENT_COUNT_TYPE AS
SELECT PAYMENT_TYPE.PAYMENT_TYPE_DEFINATION , COUNT(*) AS KULLANIM_SAYISI
  FROM PAYMENT
  INNER JOIN PAYMENT_TYPE
  ON PAYMENT_TYPE.PAYMENT_TYPE_ID = PAYMENT.PAYMENT_TYPE_ID
  GROUP BY PAYMENT_TYPE.PAYMENT_TYPE_DEFINATION;

CREATE or REPLACE VIEW VÝEW_CIYT_HOTEL AS
SELECT ADDRESS_CITY.CITY_NAME, HOTEL.HOTEL_NAME
  FROM HOTEL
  INNER JOIN ( SELECT CITY.CITY_NAME,ADDRESS.HOTEL_ID FROM ADDRESS
              INNER JOIN CITY
              ON CITY.CITY_ID = ADDRESS.CITY_ID) ADDRESS_CITY
  ON HOTEL.HOTEL_ID = ADDRESS_CITY.HOTEL_ID;

CREATE or REPLACE VIEW VÝEW_CUSTOMER_POINT AS
SELECT CUSTOMER.CUSTOMER_NAME,CUSTOMER.CUSTOMER_SURNAME,CUSTOMER_CARD.CARD_POINT
  FROM CUSTOMER
  INNER JOIN CUSTOMER_CARD
  ON CUSTOMER_CARD.CUSTOMER_TC = CUSTOMER.TC;
  
CREATE or REPLACE VIEW VÝEW_CUSTOMER_LOGIN AS
SELECT DISTINCT MEMBER_TABLE.MEMBER_ID, MEMBER_TABLE.MEMBER_MAIL, MEMBER_TABLE.MEMBER_PHONE_NUMBER
  FROM MEMBER_TABLE
  INNER JOIN LOGIN_LOG
  ON MEMBER_TABLE.MEMBER_ID = LOGIN_LOG.MEMBER_ID
  WHERE TRUNC(LOGIN_LOG.LOGIN_DATE) = TRUNC(SYSDATE);  